# Generated by Django 4.2.3 on 2023-08-02 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postsapp', '0002_remove_topic_user_usertopic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertopic',
            old_name='preferred',
            new_name='prefer',
        ),
    ]
