# Generated by Django 4.2.3 on 2023-08-03 02:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postsapp', '0003_rename_preferred_usertopic_prefer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertopic',
            name='prefer',
        ),
        migrations.AddField(
            model_name='topic',
            name='users',
            field=models.ManyToManyField(through='postsapp.UserTopic', to=settings.AUTH_USER_MODEL),
        ),
    ]
