# Generated by Django 4.2.3 on 2023-08-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postsapp', '0004_remove_usertopic_prefer_topic_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='topic',
            new_name='topics',
        ),
    ]
