# Generated by Django 4.2.3 on 2023-08-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsapp', '0006_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
