# Generated by Django 4.2.3 on 2023-08-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postsapp', '0007_alter_topic_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertopic',
            options={'ordering': ['-notify']},
        ),
    ]
