# Generated by Django 4.2.3 on 2023-08-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postsapp', '0009_alter_usertopic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertopic',
            options={},
        ),
    ]
