# Generated by Django 4.2.3 on 2023-08-13 12:45

from django.db import migrations, models
from django.utils.text import slugify


def populate_slug(apps, schema_editor):
    Article = apps.get_model('postsapp', 'Article')
    for article in Article.objects.all():
        article.slug = slugify(f"{article.title[:36]} {article.created_at.strftime('%Y-%d-%m')}")
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ('postsapp', '0011_article_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slug),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
